from __future__ import annotations

from typing import Any, Protocol


class Store(Protocol):
    @property
    def mode(self) -> str: ...

    def list_chats(self, user_id: str) -> list[dict[str, Any]]: ...

    def list_messages(self, user_id: str) -> list[dict[str, Any]]: ...

    def list_messages_for_chat(self, user_id: str, chat_id: str) -> list[dict[str, Any]]: ...

    def list_context_edges(self, user_id: str) -> list[dict[str, Any]]: ...

    def create_chat(
        self, user_id: str, title: str, position_x: float, position_y: float
    ) -> dict[str, Any]: ...

    def update_chat_title(self, user_id: str, chat_id: str, title: str) -> None: ...

    def delete_chat(self, user_id: str, chat_id: str) -> None: ...

    def create_message(
        self, user_id: str, chat_id: str, role: str, text: str
    ) -> dict[str, Any]: ...

    def delete_message(self, user_id: str, message_id: str) -> None: ...

    def update_chat_positions(
        self, user_id: str, positions: dict[str, tuple[float, float]]
    ) -> None: ...

    def replace_context_edges(self, user_id: str, edges: list[dict[str, Any]]) -> None: ...
