from __future__ import annotations

import base64
from typing import Any

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

try:
    from supabase import Client
except ModuleNotFoundError:  # pragma: no cover - optional in local/test environments
    Client = Any  # type: ignore[assignment,misc]

from services.backboard_service import BackboardClient
from settings import Settings
from store.base import Store

bearer_scheme = HTTPBearer(auto_error=False)


def get_supabase_admin(request: Request) -> Client | None:
    return getattr(request.app.state, "supabase_admin", None)


def get_settings(request: Request) -> Settings:
    settings = getattr(request.app.state, "settings", None)
    assert settings is not None, "Settings not initialized on app.state"
    return settings


def _extract_user_id(user: Any) -> str | None:
    if isinstance(user, dict):
        uid = user.get("id")
        return str(uid) if uid else None
    uid = getattr(user, "id", None)
    return str(uid) if uid else None


def _decode_base64_url(value: str) -> str | None:
    padding = "=" * ((4 - (len(value) % 4)) % 4)
    try:
        decoded = base64.urlsafe_b64decode(value + padding)
        return decoded.decode("utf-8")
    except Exception:
        return None


def _resolve_dev_bypass_user_id(token: str) -> str | None:
    prefix = "dev-bypass:"
    if not token.startswith(prefix):
        return None
    encoded_email = token[len(prefix) :].strip()
    if not encoded_email:
        return None
    email = _decode_base64_url(encoded_email)
    if not email:
        return None
    return f"dev:{email.strip().lower()}"


def get_user_id(
    credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),  # noqa: B008
    supabase_admin: Client | None = Depends(get_supabase_admin),  # noqa: B008
    settings: Settings = Depends(get_settings),  # noqa: B008
) -> str:
    if credentials is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing bearer token",
        )

    token = credentials.credentials

    # Dev bypass: accepts synthetic tokens generated by the web app when AUTH_DEV_BYPASS=true.
    if settings.auth_dev_bypass:
        maybe_dev_user_id = _resolve_dev_bypass_user_id(token)
        if maybe_dev_user_id is not None:
            return maybe_dev_user_id

    if supabase_admin is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Supabase auth is not configured on the backend",
        )

    try:
        response = supabase_admin.auth.get_user(token)
    except Exception as exc:  # pragma: no cover - provider/network specific
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired auth token",
        ) from exc

    user = getattr(response, "user", None)
    user_id = _extract_user_id(user)
    if user_id is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Unable to resolve user from auth token",
        )

    return user_id


def get_store(request: Request) -> Store:
    store = getattr(request.app.state, "store", None)
    assert store is not None, "Store not initialized on app.state"
    return store


def get_metrics(request: Request) -> Any:
    metrics = getattr(request.app.state, "metrics", None)
    assert metrics is not None, "Metrics not initialized on app.state"
    return metrics


def get_backboard_client(request: Request) -> BackboardClient:
    client = getattr(request.app.state, "backboard_client", None)
    assert client is not None, "Backboard client not initialized on app.state"
    return client
